version: "3"
services:

    postgres:
        image: "library/postgres:9.6"

        environment:
            POSTGRES_USER: "dev"
            POSTGRES_PASSWORD: "dev"

        ports:
          - "5432:5432"
